# -*- coding: utf-8 -*-
"""customers_per_hour.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCog3uBSeham9L8dMgBr4MAaLMmPTQdQ
"""

import pandas as pd
import numpy as np

## Loading the data
path='https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx'
data=pd.read_excel(path)

## CustomerID is loaded as float. Changing it to int
data['CustomerID'] = data['CustomerID'].apply(lambda x: int(x) if x == x else "")

## Creating Date and Hour columns from the timestamp InvoiceDate
## Here Hour is the truncated time of the day. if the time is hh:mm:ss, Hour is hh only.
data['Date']=[d.date() for d in data['InvoiceDate']]
data['Hour']=[d.hour for d in data['InvoiceDate']]

#data.head(10)

## Columns of our interest
dateTimeData=data[['CustomerID','Date','Hour']]

## Counting number of customers in a particular Date and Hour
table=dateTimeData.groupby(['Date','Hour']).agg({"CustomerID": "nunique"})

## Converting grouped object to DataFrame
tab2=pd.DataFrame(table.reset_index())

#tab2.head()

## Creating the required DataFrame with columns Date, Count1, Count2,...Count24.
## Counti represents the time between hour i-1(inclusive) and i(exclusive)
colNames=['Date']
colNames.extend(['Count'+str(k+1) for k in range(24)])
newDf=pd.DataFrame(columns=colNames)
for date in set(tab2['Date']):
  tab3=tab2[tab2['Date']==date][['Hour','CustomerID']]
  newRow=[date]
  newRow.extend([0 for k in range(24)])
  for hr in tab3['Hour']:
    newRow[int(hr)+1]=int(tab3[tab3['Hour']==hr]['CustomerID'])
  #print(pd.DataFrame([newRow],columns=colNames))
  newDf=newDf.append(pd.DataFrame([newRow],columns=colNames),ignore_index=True)

newDf=newDf.sort_values(by=['Date']).reset_index()

newDf=newDf.drop('index',axis=1)

newDf.to_csv('customers_per_hour.csv')