# -*- coding: utf-8 -*-
"""transactions_per_hour.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ufi-kdrNjBZNxYZ_-NUDWM63_CsdttU-
"""

import pandas as pd
#import numpy as np

path='https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx'
data=pd.read_excel(path)

data['Date']=[d.date() for d in data['InvoiceDate']]
data['Hour']=[d.hour for d in data['InvoiceDate']]

dateTime=data[['Date','Hour']]

table=dateTime.groupby(['Date','Hour']).size()

tab2=pd.DataFrame(table.reset_index())

colNames=['Date']
colNames.extend(['Count'+str(k+1) for k in range(24)])
newDf=pd.DataFrame(columns=colNames)
for date in set(tab2['Date']):
  tab3=tab2[tab2['Date']==date][['Hour',0]]
  newRow=[date]
  newRow.extend([0 for k in range(24)])
  for hr in tab3['Hour']:
    newRow[int(hr)+1]=int(tab3[tab3['Hour']==hr][0])
  #print(pd.DataFrame([newRow],columns=colNames))
  newDf=newDf.append(pd.DataFrame([newRow],columns=colNames),ignore_index=True)

newDf=newDf.sort_values(by=['Date']).reset_index()
newDf=newDf.drop('index',axis=1)

newDf.to_csv('transaction_per_hour.csv')